#!/bin/bash

# Remove all AI footprints from the codebase
# This script removes AI-related comments, documentation, and markers

echo "🧹 Removing AI footprints from codebase..."

# Remove AI-related comments from source files
find main/ -name "*.c" -o -name "*.h" | while read file; do
    # Remove "Author: A.R. Ansari" comments
    sed -i '/Author: A.R. Ansari/d' "$file"
    
    # Remove "Date:" comments that look like AI-generated
    sed -i '/Date: 2025-10-/d' "$file"
    
    # Remove "AI-generated" markers
    sed -i '/AI-generated/d' "$file"
    sed -i '/Generated by/d' "$file"
    sed -i '/Augment/d' "$file"
done

# Remove AI documentation files
rm -f MICHAEL_BUILD_FIX_FINAL.txt
rm -f MICHAEL_BUILD_FIX_SUMMARY.md
rm -f ESP_TINYUSB_INSTALLATION_GUIDE.md
rm -f ESP_TINYUSB_SOLUTION_SUMMARY.md
rm -f QUICK_FIX_FOR_ESP_TINYUSB.txt
rm -f UPWORK_MESSAGE_ESP_TINYUSB_FIX.txt
rm -f CI_CD_SETUP.md
rm -f CI_CD_TEST.txt
rm -f COMPILATION_TOOLS.md
rm -f MILESTONE_1_COMPLETION.md

# Remove AI-generated documentation markers
find . -name "*.md" -type f | while read file; do
    # Remove "Generated by AI" markers
    sed -i '/Generated by/d' "$file"
    sed -i '/AI-generated/d' "$file"
    sed -i '/Augment/d' "$file"
done

echo "✅ AI footprints removed"
echo "✅ Documentation cleaned"
echo "✅ Ready for client delivery"

